/**
 * apps/web/src/lib/packet/zip.ts
 *
 * Create a ZIP archive containing multiple document files.
 */

import JSZip from 'jszip'
import type { DocumentFile } from './types'

/**
 * Create a ZIP buffer from an array of DocumentFile objects.
 * Each file is added to the ZIP with its filename.
 */
export async function createPacketZIP(files: DocumentFile[]): Promise<Buffer> {
  const zip = new JSZip()

  for (const file of files) {
    zip.file(file.filename, file.buffer)
  }

  // Add a README.txt with disclaimer
  zip.file(
    'README.txt',
    [
      'MESSENGINFO — Document Translation Packet',
      '==========================================',
      '',
      'This packet contains:',
      ...files.map((f) => `  - ${f.filename}`),
      '',
      'IMPORTANT NOTICES:',
      '- This is a translator-signed draft template, not a formal translation certification service.',
      '- Per 8 CFR 103.2(b)(3), USCIS generally requires a complete English translation with',
      '  a signed self-certification statement. You must print, complete, and sign the included template.',
      '- This document is for informational purposes only.',
      '- NOT LEGAL ADVICE. Consult a licensed immigration attorney.',
      '',
      `Generated by Messenginfo (messenginfo.com)`,
      `Date: ${new Date().toISOString().split('T')[0]}`,
    ].join('\n')
  )

  const zipBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  })

  return Buffer.from(zipBuffer)
}
