/**
 * Generate 4 downloadable HTML output files for the Translation Lab.
 *
 * File 1: translation-draft.html         — USCIS translation per 8 CFR 103.2(b)(3)
 * File 2: field-review-checklist.html    — AI extraction results + user corrections table
 * File 3: certification-statement.html   — standalone self-certification template to print and sign
 * File 4: filing-instructions.html       — step-by-step filing guide
 *
 * All are self-contained HTML (no external dependencies).
 * Browser: File → Print → Save as PDF works on all.
 */

import type { OCRResult, OCRField } from './mockOCR'
import type { SampleDocument } from './sampleDocuments'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

function today(): string {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function statusBadge(status: OCRField['status'], confidence: number): string {
  const colors: Record<OCRField['status'], string> = {
    pass:   '#16a34a',
    review: '#ca8a04',
    fail:   '#dc2626',
  }
  const labels: Record<OCRField['status'], string> = {
    pass:   'PASS',
    review: 'REVIEW',
    fail:   'FAIL',
  }
  return `<span style="background:${colors[status]};color:#fff;padding:2px 7px;border-radius:4px;font-size:10px;font-weight:bold">${labels[status]} ${confidence}%</span>`
}

function pageHeader(title: string, subtitle: string): string {
  return `
    <div style="border-bottom:2px solid #1D5CBB;padding-bottom:12px;margin-bottom:18px">
      <h1 style="font-size:15pt;font-weight:bold;text-align:center;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px">${esc(title)}</h1>
      <p style="font-size:10pt;text-align:center;color:#555">${esc(subtitle)}</p>
      <p style="font-size:9pt;text-align:center;color:#888;margin-top:4px">Generated by Messenginfo · ${today()} · messenginfo.com</p>
    </div>`
}

function draftBanner(): string {
  return `<div style="background:#fff8e1;border:1.5px solid #f59e0b;border-radius:4px;padding:8px 12px;margin-bottom:14px;font-size:10pt;color:#92400e;text-align:center">
    ⚠ DRAFT TEMPLATE — Review and sign before submitting to USCIS (8 CFR 103.2(b)(3))
  </div>`
}

const PAGE_STYLES = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Times New Roman', Times, serif;
    font-size: 12pt; line-height: 1.5; color: #000;
    background: #fff; max-width: 740px;
    margin: 0 auto; padding: 40px 30px 60px;
  }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { background: #f5f5f5; font-size: 10pt; font-weight: bold; padding: 6px 10px; text-align: left; border: 1px solid #ccc; }
  td { padding: 7px 10px; border: 1px solid #ddd; font-size: 11pt; vertical-align: top; }
  .label { width: 42%; color: #333; font-style: italic; }
  .value { color: #000; font-weight: 500; }
  .section { font-size: 10pt; font-weight: bold; text-transform: uppercase; letter-spacing: .06em; color: #555; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin: 16px 0 10px; }
  .cert-block { border: 1.5px solid #000; padding: 16px 18px; margin-top: 22px; border-radius: 2px; }
  .cert-block h2 { font-size: 13pt; font-weight: bold; text-transform: uppercase; margin-bottom: 10px; text-align: center; }
  .sign-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px 24px; margin-top: 14px; }
  .sign-line { border-bottom: 1px solid #000; padding-bottom: 2px; min-height: 28px; }
  .sign-label { font-size: 9.5pt; color: #444; margin-top: 3px; }
  .footer { margin-top: 28px; padding-top: 10px; border-top: 1px solid #ccc; font-size: 9pt; color: #666; text-align: center; }
  @media print { body { padding: 20px; } }
`

function wrapPage(bodyContent: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>${PAGE_STYLES}</style>
</head>
<body>${bodyContent}</body>
</html>`
}

// ---------------------------------------------------------------------------
// File 1: Translation Draft
// ---------------------------------------------------------------------------

export function generateTranslationDraft(
  sample: SampleDocument,
  result: OCRResult,
  sourceLanguage: string,
): string {
  const fieldMap = Object.fromEntries(result.fields.map((f) => [f.key, f.editedValue]))

  const fieldRows = result.fields
    .filter((f) => f.editedValue?.trim())
    .map((f) => `
      <tr>
        <td class="label">${esc(f.labelEn)}</td>
        <td class="value">${esc(f.editedValue)}</td>
      </tr>`)
    .join('')

  const body = `
    ${pageHeader(`Translation of ${sample.titleEn}`, `Original language: ${sourceLanguage} → English`)}
    ${draftBanner()}

    <div class="section">Document Information</div>
    <table>
      <tr><td class="label">Document Type</td><td class="value">${esc(sample.titleEn)}</td></tr>
      <tr><td class="label">Original Language</td><td class="value">${esc(sourceLanguage)}</td></tr>
      <tr><td class="label">Target Language</td><td class="value">English</td></tr>
      <tr><td class="label">Date of Translation</td><td class="value">${today()}</td></tr>
    </table>

    <div class="section">Document Fields — English Translation</div>
    <table>
      <thead>
        <tr><th>Field</th><th>Translation / Value</th></tr>
      </thead>
      <tbody>
        ${fieldRows || '<tr><td colspan="2" style="color:#999;text-align:center">No fields entered.</td></tr>'}
      </tbody>
    </table>

    <div class="cert-block">
      <h2>Translator Certification</h2>
      <p style="font-size:11pt;margin-bottom:12px;line-height:1.6">
        Pursuant to <strong>8 CFR 103.2(b)(3)</strong>, I certify that I am competent to translate
        from <strong>${esc(sourceLanguage)}</strong> into <strong>English</strong>, and that
        the above translation is complete and accurate to the best of my knowledge and belief.
      </p>
      <div class="sign-grid">
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Signature of Translator</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Date</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Printed Full Name</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Phone / Email (optional)</div></div>
        <div style="grid-column:1/-1"><div class="sign-line">&nbsp;</div><div class="sign-label">Mailing Address</div></div>
        <div style="grid-column:1/-1"><div class="sign-line">&nbsp;</div><div class="sign-label">City, State, ZIP Code</div></div>
      </div>
    </div>

    <div class="footer">
      Prepared with Messenginfo · messenginfo.com · Draft template only — not a certified translation.<br>
      Translation requirements: 8 CFR 103.2(b)(3) · uscis.gov · Generated: ${today()}
    </div>`

  return wrapPage(body)
}

// ---------------------------------------------------------------------------
// File 2: Field Review Checklist
// ---------------------------------------------------------------------------

export function generateReviewChecklist(
  sample: SampleDocument,
  result: OCRResult,
): string {
  const rows = result.fields.map((f) => {
    const edited = f.editedValue !== f.aiValue
    const rowBg = f.status === 'pass' ? '' : f.status === 'review' ? 'background:#fffbeb' : 'background:#fff5f5'
    return `
      <tr style="${rowBg}">
        <td class="label">${esc(f.labelEn)}</td>
        <td style="font-size:10pt;color:#555">${esc(f.aiValue)}</td>
        <td style="font-size:10pt">${edited ? `<strong>${esc(f.editedValue)}</strong> <span style="color:#16a34a;font-size:9pt">✏ corrected</span>` : esc(f.editedValue)}</td>
        <td style="text-align:center">${statusBadge(f.status, f.confidence)}</td>
        ${f.note ? `<td style="font-size:9pt;color:#666;font-style:italic">${esc(f.note)}</td>` : '<td style="color:#aaa">—</td>'}
      </tr>`
  }).join('')

  const body = `
    ${pageHeader('Field Extraction Review Checklist', `${sample.titleEn} — AI Extraction Audit`)}

    <p style="font-size:11pt;margin-bottom:16px">
      This checklist shows each field extracted by AI, the original extracted value,
      the final confirmed value, confidence score, and any extraction notes.
      Fields marked <strong style="color:#ca8a04">REVIEW</strong> or
      <strong style="color:#dc2626">FAIL</strong> require manual verification.
    </p>

    <table>
      <thead>
        <tr>
          <th>Field</th>
          <th>AI Extracted</th>
          <th>Final Value</th>
          <th style="text-align:center">Confidence</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>

    <div style="background:#f5f5f5;border:1px solid #ddd;padding:12px 16px;border-radius:4px;font-size:10pt;margin-top:8px">
      <strong>Summary:</strong>
      &nbsp;&nbsp;✅ PASS: ${result.passCount}
      &nbsp;&nbsp;⚠️ REVIEW: ${result.reviewCount}
      &nbsp;&nbsp;❌ FAIL: ${result.failCount}
      &nbsp;&nbsp;|&nbsp;&nbsp;Overall AI confidence: <strong>${result.overallConfidence}%</strong>
      &nbsp;&nbsp;|&nbsp;&nbsp;Processing time: ${result.processingMs}ms
    </div>

    <div class="footer">
      Prepared with Messenginfo · messenginfo.com · ${today()}<br>
      Keep this checklist with your translation draft for your records.
    </div>`

  return wrapPage(body)
}

// ---------------------------------------------------------------------------
// File 3: Standalone Certification Statement
// ---------------------------------------------------------------------------

export function generateCertificationStatement(
  sample: SampleDocument,
  sourceLanguage: string,
): string {
  const body = `
    ${pageHeader('Self-Certification Statement', `8 CFR 103.2(b)(3) — Required for USCIS Submissions`)}
    ${draftBanner()}

    <p style="font-size:11pt;margin-bottom:20px;line-height:1.7">
      The following certification statement must accompany any foreign-language document
      submitted to USCIS. The translator must complete and sign this statement.
      USCIS requires a full English translation and a signed self-certification statement
      for each foreign-language document (8 CFR 103.2(b)(3)).
    </p>

    <div class="cert-block">
      <h2>Self-Certification Statement</h2>
      <p style="font-size:11pt;margin-bottom:16px;line-height:1.7">
        I, <span style="display:inline-block;width:220px;border-bottom:1px solid #000">&nbsp;</span>,
        certify that I am competent to translate from <strong>${esc(sourceLanguage)}</strong>
        into <strong>English</strong>, and that the English translation of the
        <strong>${esc(sample.titleEn)}</strong> attached hereto is a complete and accurate
        translation to the best of my knowledge and belief.
      </p>
      <p style="font-size:11pt;margin-bottom:16px">
        I further certify that I have no financial or other interest in the outcome of any
        matter for which this translation is submitted.
      </p>
      <div class="sign-grid">
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Signature of Translator</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Date Signed</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Printed Full Name</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Language(s) Translated</div></div>
        <div style="grid-column:1/-1"><div class="sign-line">&nbsp;</div><div class="sign-label">Mailing Address (Street)</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">City</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">State &amp; ZIP Code</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Phone Number</div></div>
        <div><div class="sign-line">&nbsp;</div><div class="sign-label">Email Address</div></div>
      </div>
    </div>

    <div style="background:#fff8e1;border:1px solid #f59e0b;padding:12px 16px;border-radius:4px;font-size:10pt;color:#92400e;margin-top:16px">
      <strong>⚠ Important:</strong> The translator must be a person — you, a friend, a family member,
      or a professional. You do not need to be a licensed translator. However, you must be
      fluent in both languages and sign this statement in your own name.
      Messenginfo does not certify translations and is not the translator of record.
    </div>

    <div class="footer">
      Prepared with Messenginfo · messenginfo.com · ${today()}<br>
      Reference: 8 CFR 103.2(b)(3) · uscis.gov · For informational use only.
    </div>`

  return wrapPage(body)
}

// ---------------------------------------------------------------------------
// File 4: Filing Instructions
// ---------------------------------------------------------------------------

export function generateFilingInstructions(
  sample: SampleDocument,
  sourceLanguage: string,
): string {
  const steps = [
    {
      n: 1,
      title: 'Print all documents',
      detail: 'Print: (1) Translation Draft, (2) Field Review Checklist, (3) Certification Statement. Use standard white letter-size paper (8.5" × 11"). Print on one side only.',
    },
    {
      n: 2,
      title: 'Complete the Certification Statement',
      detail: 'Fill in your full name, address, phone, and email in the blank lines on the Certification Statement. Then sign in ink by hand. Signature must be original (not typed or printed).',
    },
    {
      n: 3,
      title: 'Arrange your document packet',
      detail: 'Arrange in this order: (1) Certification Statement on top, (2) Translation Draft, (3) Copy or original of the foreign-language document (your passport, certificate, etc.).',
    },
    {
      n: 4,
      title: 'Submit with your USCIS application',
      detail: 'Include this translation packet with your USCIS application. Do not send original documents — send certified true copies unless specifically required. Retain originals for yourself.',
    },
    {
      n: 5,
      title: 'Keep a copy',
      detail: 'Make a complete copy of your entire submission packet (application + all attachments) before mailing or submitting online. Keep this copy for your records for at least 3 years.',
    },
  ]

  const stepHtml = steps.map((s) => `
    <div style="display:flex;gap:14px;margin-bottom:16px;align-items:flex-start">
      <div style="width:30px;height:30px;border-radius:50%;background:#1D5CBB;color:#fff;font-weight:bold;font-size:13pt;display:flex;align-items:center;justify-content:center;flex-shrink:0">${s.n}</div>
      <div>
        <p style="font-size:12pt;font-weight:bold;margin-bottom:4px">${esc(s.title)}</p>
        <p style="font-size:11pt;color:#333;line-height:1.6">${esc(s.detail)}</p>
      </div>
    </div>`).join('')

  const body = `
    ${pageHeader('Filing Instructions', `${sample.titleEn} Translation — ${sourceLanguage} → English`)}

    <p style="font-size:11pt;margin-bottom:20px;line-height:1.7">
      Follow these steps to correctly prepare and submit your translated
      <strong>${esc(sample.titleEn)}</strong> to USCIS.
      Translation requirements are governed by <strong>8 CFR 103.2(b)(3)</strong>.
    </p>

    ${stepHtml}

    <div style="background:#f0f9ff;border:1.5px solid #0ea5e9;padding:14px 16px;border-radius:4px;font-size:11pt;margin-top:10px">
      <strong>📋 Your translation package checklist:</strong>
      <ul style="margin-top:8px;padding-left:20px;line-height:2">
        <li>✅ Translation Draft (.html printed to PDF)</li>
        <li>✅ Self-Certification Statement (signed in ink)</li>
        <li>✅ Copy of original ${esc(sample.titleEn)} in ${esc(sourceLanguage)}</li>
        <li>✅ Included with main USCIS application</li>
      </ul>
    </div>

    <div style="background:#fff5f5;border:1px solid #fca5a5;padding:12px 16px;border-radius:4px;font-size:10pt;color:#991b1b;margin-top:16px">
      <strong>⚠ Not Legal Advice.</strong>
      This guide is for informational purposes only. Messenginfo is not a law firm
      and cannot provide legal advice. For complex immigration matters, consult a
      licensed immigration attorney or accredited representative.
    </div>

    <div class="footer">
      Prepared with Messenginfo · messenginfo.com · ${today()}<br>
      Reference: 8 CFR 103.2(b)(3), USCIS Policy Manual · uscis.gov
    </div>`

  return wrapPage(body)
}

// ---------------------------------------------------------------------------
// Trigger browser download of a generated file
// ---------------------------------------------------------------------------

export function downloadLabFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// Generate all 4 files at once and return as a map
// ---------------------------------------------------------------------------

export interface LabOutputs {
  translationDraft: string
  reviewChecklist: string
  certificationStatement: string
  filingInstructions: string
}

export function generateAllLabOutputs(
  sample: SampleDocument,
  result: OCRResult,
  sourceLanguage: string,
): LabOutputs {
  return {
    translationDraft:       generateTranslationDraft(sample, result, sourceLanguage),
    reviewChecklist:        generateReviewChecklist(sample, result),
    certificationStatement: generateCertificationStatement(sample, sourceLanguage),
    filingInstructions:     generateFilingInstructions(sample, sourceLanguage),
  }
}
