/**
 * I-131 field-by-field validation harness (Phase 2B, Agent 2).
 *
 * Validates EVERY I-131 field the Re-Parole mapper touches, source →
 * mapper → PrefillOp → generated PDF → AcroForm readback, against the
 * edition-locked official PDF (Edition 01/20/25).
 *
 * Synthetic answers ONLY — no PII, no real-document ground truth in this
 * file. Verdicts are asserted on the AcroForm value read back from the
 * generated bytes, exactly as a USCIS scanner / PDF viewer would read it.
 *
 * Special focus (per task): legal name, A-Number, DOB, country of birth,
 * citizenship, class of admission, last-arrival / I-94, gender checkbox,
 * mailing+physical address, contact. Plus source-separation guarantees:
 *   - a C3-rejected (empty) document field stays EMPTY (no fabrication)
 *   - a user answer is never overwritten by a document default
 *   - checkbox/radio values match the visible legal answer
 *   - text is not clipped
 */

import { describe, it, expect, beforeAll, vi } from 'vitest'

vi.setConfig({ testTimeout: 120_000 })

import { buildReParoleI131 } from '../packetBuilder'
import { buildI131Ops } from '../i131FieldMap'
import { I131_EDITION } from '../packetBuilder'
import type { ReParoleAnswers } from '../answers'
import { PDFDocument, PDFTextField, PDFCheckBox, PDFDropdown } from 'pdf-lib'

const FIELD = {
  family: 'form1[0].P4[0].Part2_Line1_FamilyName[0]',
  given: 'form1[0].P4[0].Part2_Line1_GivenName[0]',
  middle: 'form1[0].P4[0].Part2_Line1_MiddleName[0]',
  m_inCareOf: 'form1[0].P5[0].Part2_Line3_InCareofName[0]',
  m_street: 'form1[0].P5[0].Part2_Line3_StreetNumberName[0]',
  m_apt: 'form1[0].P5[0].Part2_Line3_AptSteFlrNumber[0]',
  m_city: 'form1[0].P5[0].Part2_Line3_CityTown[0]',
  m_state: 'form1[0].P5[0].Part2_Line3_State[0]',
  m_zip: 'form1[0].P5[0].Part2_Line3_ZipCode[0]',
  p_street: 'form1[0].P5[0].Part2_Line4_StreetNumberName[0]',
  p_city: 'form1[0].P5[0].Part2_Line4_CityTown[0]',
  p_state: 'form1[0].P5[0].Part2_Line4_State[0]',
  p_zip: 'form1[0].P5[0].Part2_Line4_ZipCode[0]',
  aNumber: 'form1[0].P5[0].#area[0].Part2_Line5_AlienNumber[0]',
  countryBirth: 'form1[0].P5[0].Part2_Line6_CountryOfBirth[0]',
  countryNat: 'form1[0].P5[0].Part2_Line7_CountryOfCitizenshiporNationality[0]',
  genderF: 'form1[0].P5[0].Part2_Line8_Gender[0]', // on-value /F
  genderM: 'form1[0].P5[0].Part2_Line8_Gender[1]', // on-value /M
  dob: 'form1[0].P5[0].Part2_Line9_DateOfBirth[0]',
  ssn: 'form1[0].P5[0].#area[1].Part2_Line10_SSN[0]',
  uscisAcct: 'form1[0].P5[0].Part2_Line11_USCISOnlineAcctNumber[0]',
  coa: 'form1[0].P5[0].Part2_Line12_ClassofAdmission[0]',
  i94: 'form1[0].P5[0].Part2_Line13_I94RecordNo[0]',
  dayPhone: 'form1[0].#subform[10].Part10_Line1_DayPhone[0]',
  mobilePhone: 'form1[0].#subform[10].Part10_Line2_MobilePhone[0]',
  email: 'form1[0].#subform[10].Part10_Line3_Email[0]',
} as const

// All-Latin synthetic answers (no transliteration noise), every optional
// field populated so the mapper exercises every branch.
const FULL: ReParoleAnswers = {
  family_name: 'Smith',
  given_name: 'John',
  middle_name: 'Edward',
  mailing_in_care_of: 'Jane Doe',
  mailing_street: '742 Evergreen Terrace',
  mailing_apt_ste_flr: 'APT 4',
  mailing_city: 'Springfield',
  mailing_state: 'IL',
  mailing_zip: '62704',
  physical_same_as_mailing: false,
  physical_street: '100 Industrial Rd',
  physical_apt_ste_flr: 'STE 2',
  physical_city: 'Shelbyville',
  physical_state: 'IL',
  physical_zip: '62565',
  a_number: 'A123456789',
  country_of_birth: 'Ukraine',
  country_of_nationality: 'Ukraine',
  sex: 'M',
  dob: '1985-07-12',
  ssn: '123-45-6789',
  uscis_online_account_number: '123456789012', // 12-digit account number (field maxLength=12)
  class_of_admission: 'UH',
  i94_admission_number: '12345678901',
  daytime_phone: '(202) 555-0143',
  mobile_phone: '202-555-0199',
  email: 'john.smith@example.com',
  filing_method: 'mail',
}

async function fill(a: ReParoleAnswers) {
  const r = await buildReParoleI131(a)
  const doc = await PDFDocument.load(r.i131_bytes)
  const form = doc.getForm()
  return {
    result: r,
    text: (name: string) => {
      const field = form.getField(name)
      // I-131 state pickers render as /Ch dropdowns; the rest are /Tx text.
      if (field instanceof PDFDropdown) return field.getSelected()[0] ?? ''
      return (field as PDFTextField).getText() ?? ''
    },
    isChecked: (name: string) => (form.getField(name) as PDFCheckBox).isChecked(),
    has: (name: string) => {
      try {
        form.getField(name)
        return true
      } catch {
        return false
      }
    },
  }
}

describe('I-131 edition lock', () => {
  it('field map targets Edition 01/20/25', () => {
    expect(I131_EDITION).toBe('01/20/25')
  })
})

describe('I-131 field-by-field: document-derived + user-declared (full answers)', () => {
  let f: Awaited<ReturnType<typeof fill>>
  beforeAll(async () => {
    f = await fill(FULL)
  })

  it('Part 2 Item 1 — legal name (family/given/middle) SAME', () => {
    expect(f.text(FIELD.family)).toBe('Smith')
    expect(f.text(FIELD.given)).toBe('John')
    expect(f.text(FIELD.middle)).toBe('Edward')
  })

  it('Part 2 Item 3 — mailing address SAME (in-care-of, street, apt, city, state, zip)', () => {
    expect(f.text(FIELD.m_inCareOf)).toBe('Jane Doe')
    expect(f.text(FIELD.m_street)).toBe('742 Evergreen Terrace')
    expect(f.text(FIELD.m_apt)).toBe('APT 4')
    expect(f.text(FIELD.m_city)).toBe('Springfield')
    expect(f.text(FIELD.m_state)).toBe('IL')
    expect(f.text(FIELD.m_zip)).toBe('62704')
  })

  it('Part 2 Item 4 — physical address written ONLY when different from mailing', () => {
    expect(f.text(FIELD.p_street)).toBe('100 Industrial Rd')
    expect(f.text(FIELD.p_city)).toBe('Shelbyville')
    expect(f.text(FIELD.p_state)).toBe('IL')
    expect(f.text(FIELD.p_zip)).toBe('62565')
  })

  it('Part 2 Item 5 — A-Number normalized to 9 digits (no "A", no hyphens; field maxLength=9)', () => {
    // Regression: raw "A123456789" (10 chars) was rejected by maxLength=9 and
    // the whole field was silently dropped. Mapper now strips to bare digits.
    expect(f.text(FIELD.aNumber)).toBe('123456789')
  })

  it('Part 2 Item 6/7 — country of birth + citizenship SAME', () => {
    expect(f.text(FIELD.countryBirth)).toBe('Ukraine')
    expect(f.text(FIELD.countryNat)).toBe('Ukraine')
  })

  it('Part 2 Item 8 — gender checkbox matches the legal answer (sex=M → /M box)', () => {
    // HARD-FAIL guard: the AcroForm widget index order is the REVERSE of the
    // visible "Male Female" label order. [0]=/F, [1]=/M. A bare index swap
    // silently inverts a legal answer. Assert on the semantic on-value.
    expect(f.isChecked(FIELD.genderM)).toBe(true) // /M box checked for Male
    expect(f.isChecked(FIELD.genderF)).toBe(false) // /F box must NOT be checked
  })

  it('Part 2 Item 9 — DOB reformatted YYYY-MM-DD → MM/DD/YYYY', () => {
    expect(f.text(FIELD.dob)).toBe('07/12/1985')
  })

  it('Part 2 Item 10/11 — SSN normalized to 9 digits; USCIS online account SAME', () => {
    // Regression: dashed "123-45-6789" (11 chars) was rejected by maxLength=9
    // and dropped. Mapper now strips hyphens.
    expect(f.text(FIELD.ssn)).toBe('123456789')
    expect(f.text(FIELD.uscisAcct)).toBe('123456789012')
  })

  it('Part 2 Item 12/13 — class of admission + I-94 record number SAME', () => {
    expect(f.text(FIELD.coa)).toBe('UH')
    expect(f.text(FIELD.i94)).toBe('12345678901')
  })

  it('Part 10 — phones digits-only, email SAME, no clipping', () => {
    expect(f.text(FIELD.dayPhone)).toBe('2025550143')
    expect(f.text(FIELD.mobilePhone)).toBe('2025550199')
    expect(f.text(FIELD.email)).toBe('john.smith@example.com')
  })
})

describe('I-131 gender — female answer hits the /F box', () => {
  it('sex=F → /F box checked, /M box NOT checked', async () => {
    const f = await fill({ ...FULL, sex: 'F' })
    expect(f.isChecked(FIELD.genderF)).toBe(true)
    expect(f.isChecked(FIELD.genderM)).toBe(false)
  })

  it('sex="" (unknown / C3-rejected) → NEITHER gender box checked (no fabrication)', async () => {
    const f = await fill({ ...FULL, sex: '' })
    expect(f.isChecked(FIELD.genderF)).toBe(false)
    expect(f.isChecked(FIELD.genderM)).toBe(false)
  })

  it('mapper emits exactly ONE gender op and it carries the matching on-value index', () => {
    const opsM = buildI131Ops({ ...FULL, sex: 'M' }).filter((o) => o.field.includes('Part2_Line8_Gender'))
    const opsF = buildI131Ops({ ...FULL, sex: 'F' }).filter((o) => o.field.includes('Part2_Line8_Gender'))
    expect(opsM).toHaveLength(1)
    expect(opsF).toHaveLength(1)
    expect(opsM[0].field).toBe(FIELD.genderM) // /M widget
    expect(opsF[0].field).toBe(FIELD.genderF) // /F widget
  })
})

describe('I-131 source-separation: C3-rejected / empty document fields stay EMPTY', () => {
  // Simulates the canonical pipeline rejecting document facts (finalValue=null
  // → empty string arriving at the packet boundary). The mapper must NOT
  // fabricate, default, or carry over a value into these document fields.
  const emptyDocFacts: ReParoleAnswers = {
    ...FULL,
    middle_name: '',
    a_number: undefined,
    country_of_birth: '',
    country_of_nationality: '',
    sex: '',
    dob: '',
    ssn: undefined,
    uscis_online_account_number: undefined,
    class_of_admission: undefined,
    i94_admission_number: undefined,
  }

  let f: Awaited<ReturnType<typeof fill>>
  beforeAll(async () => {
    f = await fill(emptyDocFacts)
  })

  it('rejected document text fields render EMPTY, never fabricated', () => {
    expect(f.text(FIELD.middle)).toBe('')
    expect(f.text(FIELD.countryBirth)).toBe('')
    expect(f.text(FIELD.countryNat)).toBe('')
    expect(f.text(FIELD.dob)).toBe('')
  })

  it('optional document fields with no value write NOTHING (stay EMPTY)', () => {
    expect(f.text(FIELD.aNumber)).toBe('')
    expect(f.text(FIELD.ssn)).toBe('')
    expect(f.text(FIELD.uscisAcct)).toBe('')
    expect(f.text(FIELD.coa)).toBe('')
    expect(f.text(FIELD.i94)).toBe('')
  })

  it('rejected gender stays EMPTY (no box silently checked)', () => {
    expect(f.isChecked(FIELD.genderF)).toBe(false)
    expect(f.isChecked(FIELD.genderM)).toBe(false)
  })

  it('user-declared fields are UNTOUCHED by document rejection', () => {
    // The applicant typed these; a rejected document fact must not erase them.
    expect(f.text(FIELD.family)).toBe('Smith')
    expect(f.text(FIELD.given)).toBe('John')
    expect(f.text(FIELD.m_street)).toBe('742 Evergreen Terrace')
    expect(f.text(FIELD.email)).toBe('john.smith@example.com')
  })
})

describe('I-131 source-separation: physical address suppressed when same as mailing', () => {
  it('physical_same_as_mailing=true → Item 4 stays EMPTY (mailing not duplicated)', async () => {
    const f = await fill({ ...FULL, physical_same_as_mailing: true })
    expect(f.text(FIELD.p_street)).toBe('')
    expect(f.text(FIELD.p_city)).toBe('')
    expect(f.text(FIELD.p_zip)).toBe('')
    // mailing still populated
    expect(f.text(FIELD.m_street)).toBe('742 Evergreen Terrace')
  })
})

describe('I-131 no-clip: long but valid values survive intact', () => {
  it('street at field maxLength (34) and a long email survive intact (no clipping)', async () => {
    const street34 = '1234 Commemorative Parkway Bldg CD' // exactly 34 chars
    expect(street34.length).toBe(34)
    const longEmail = 'firstname.lastname.with.a.very.long.local.part@subdomain.example.org'
    const f = await fill({ ...FULL, mailing_street: street34, email: longEmail })
    expect(f.text(FIELD.m_street)).toBe(street34)
    expect(f.text(FIELD.email)).toBe(longEmail)
  })
})
