import os, json, re
from pypdf import PdfReader
from pypdf.generic import IndirectObject

TPS = "/Users/sergiiivanenko/work/uscis-helper/docs/uscis/forms/tps"
PDF_DIR = os.path.join(TPS, "pdf")

FT_NAMES = {"/Tx":"text", "/Btn":"button", "/Ch":"choice", "/Sig":"signature"}

# Heuristic Part parser from USCIS field names like:
# "Pt1Line1_FamilyName[0]"  -> Part 1, Line 1, FamilyName
# "Pt2Line5a_City[0]"
# "Pt3Line2_Yes[0]"
PART_RE = re.compile(r"Pt(\d+)Line(\d+[a-z]?)_?([A-Za-z0-9]*)")

def field_records(reader):
    pages_by_field = {}
    # Map field name -> page index via /Annots traversal
    for pi, page in enumerate(reader.pages):
        annots = page.get("/Annots")
        if not annots:
            continue
        for a in annots:
            try:
                obj = a.get_object() if isinstance(a, IndirectObject) else a
                # Walk up the parent chain to assemble the full field name
                name_parts = []
                cur = obj
                seen = set()
                while cur is not None and id(cur) not in seen:
                    seen.add(id(cur))
                    nm = cur.get("/T")
                    if nm:
                        name_parts.append(str(nm))
                    par = cur.get("/Parent")
                    cur = par.get_object() if isinstance(par, IndirectObject) else par
                if name_parts:
                    full = ".".join(reversed(name_parts))
                    if full not in pages_by_field:
                        pages_by_field[full] = pi + 1
            except Exception:
                pass
    return pages_by_field

def parts_from_name(name):
    m = PART_RE.search(name or "")
    if m:
        return int(m.group(1)), m.group(2), m.group(3) or ""
    return None, None, ""

for form_key, basename in [("i-821","i-821.pdf"), ("i-765","i-765.pdf"), ("i-765ws","i-765ws.pdf"), ("i-912","i-912.pdf")]:
    path = os.path.join(PDF_DIR, basename)
    reader = PdfReader(path)
    raw = reader.get_fields() or {}
    pages = field_records(reader)

    # Build records
    records = []
    for full_name, info in raw.items():
        ft = info.get("/FT") if isinstance(info, dict) else None
        ftype = FT_NAMES.get(str(ft), "unknown")
        # Buttons: distinguish checkbox vs radio
        if ftype == "button":
            ff = info.get("/Ff") if isinstance(info, dict) else None
            try:
                flag = int(ff) if ff is not None else 0
            except Exception:
                flag = 0
            # bit 16 (0x10000): radio; bit 17 (0x20000): pushbutton
            if flag & 0x8000:
                ftype = "radio"
            elif flag & 0x10000:
                ftype = "pushbutton"
            else:
                ftype = "checkbox"
        part, line, label = parts_from_name(full_name)
        record = {
            "field_name": full_name,
            "field_type": ftype,
            "page": pages.get(full_name, None),
            "part_number": part,
            "line_number": line,
            "label_hint": label,
        }
        records.append(record)
    # Sort by page, then part, then line
    def sort_key(r):
        return (r["page"] or 999, r["part_number"] or 999, r["line_number"] or "")
    records.sort(key=sort_key)

    # Write JSON
    json_path = os.path.join(TPS, f"field_inventory_{form_key.replace('-','')}.json")
    with open(json_path, "w") as f:
        json.dump({"form": form_key, "field_count": len(records), "fields": records}, f, indent=2)

    # Write Markdown
    md_path = os.path.join(TPS, f"field_inventory_{form_key.replace('-','')}.md")
    counts_by_type = {}
    counts_by_part = {}
    for r in records:
        counts_by_type[r["field_type"]] = counts_by_type.get(r["field_type"], 0) + 1
        if r["part_number"]:
            counts_by_part[r["part_number"]] = counts_by_part.get(r["part_number"], 0) + 1
    with open(md_path, "w") as f:
        f.write(f"# Field Inventory — {form_key.upper()}\n\n")
        f.write(f"Source: `{basename}` (uscis.gov/sites/default/files/document/forms/{basename})\n\n")
        f.write(f"- Total fields: **{len(records)}**\n")
        f.write(f"- By type: {counts_by_type}\n")
        f.write(f"- By part: {counts_by_part}\n\n")
        f.write("Generated by `inventory_fields.py` on download. Re-run any time the PDF edition changes.\n\n")
        f.write("---\n\n")
        cur_part = None
        for r in records:
            if r["part_number"] != cur_part:
                cur_part = r["part_number"]
                f.write(f"\n## Part {cur_part if cur_part is not None else '?'} (page {r['page']})\n\n")
                f.write("| Line | Field name | Type | Label hint |\n|---|---|---|---|\n")
            f.write(f"| {r['line_number'] or ''} | `{r['field_name']}` | {r['field_type']} | {r['label_hint']} |\n")
    print(f"{form_key}: {len(records)} unique fields -> {md_path}")

